name: Code Checks

on:
  push:

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies with Bun
        run: bun install

      - name: Install missing dependency @wharfkit/protocol-scatter
        run: bun add @wharfkit/protocol-scatter

      - name: Build Paraglide
        run: bun run build-paraglide

      - name: Sync SvelteKit
        run: bunx svelte-kit sync

      - name: Install Playwright
        run: npm install -D @playwright/test --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Launch Debug Bun Server
        run: |
          bun run dev
          curl -v http://localhost:5173 || echo "Server not responding!"

      - name: Run Playwright tests with Bunx
        run: bunx playwright test

      - name: Run Check
        run: bun run check

      - name: Lint
        run: bun run lint

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
