name: Code Checks

on:
  push:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        chain: ['jungle4', 'kylin', 'eos', 'telos', 'telostestnet', 'wax', 'waxtestnet']
    runs-on: ubuntu-latest
    name: Check against ${{ matrix.chain }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build-paraglide
      - run: make config/${{ matrix.chain }}
      - run: make check
